[package]
name = "VacayOS"
version = "0.1.0"
authors = ["apstemmer <apstemmer@hotmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.6.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"